"""Search intelligence endpoints."""

import logging
from fastapi import APIRouter, HTTPException, Depends
from sqlmodel import Session, select
from database import engine
from models import SearchInsight
from middleware.auth import get_current_user, AuthContext

router = APIRouter(prefix="/api/search", tags=["search"])
logger = logging.getLogger(__name__)


def get_db():
    with Session(engine) as session:
        yield session


@router.get("/insights")
def get_search_insights(
    auth: AuthContext = Depends(get_current_user),
    skip: int = 0,
    limit: int = 50,
    momentum_filter: str = None,  # rising|falling|steady|no_data|null=all
    session: Session = Depends(get_db)
):
    """
    Fetch search insights generated by the cross-reference LLM pass.
    
    Query params:
        - skip: pagination offset
        - limit: max results (default 50)
        - momentum_filter: filter by trends momentum (optional)
    
    Returns:
        List of SearchInsight rows with topic, position, trends momentum, reasoning
    """
    try:
        query = select(SearchInsight).where(SearchInsight.organization_id == auth.org_id)
        
        if momentum_filter and momentum_filter in ["rising", "falling", "steady", "no_data"]:
            query = query.where(SearchInsight.trends_momentum == momentum_filter)
        
        query = query.order_by(SearchInsight.generated_at.desc()).offset(skip).limit(limit)
        insights = session.exec(query).all()
        
        return {
            "insights": [
                {
                    "id": insight.id,
                    "topic": insight.topic,
                    "our_gsc_position": insight.our_gsc_position,
                    "our_gsc_clicks": insight.our_gsc_clicks,
                    "trends_momentum": insight.trends_momentum,
                    "insight_text": insight.insight_text,
                    "generated_at": insight.generated_at.isoformat(),
                }
                for insight in insights
            ],
            "total_count": session.exec(
                select(SearchInsight).where(SearchInsight.organization_id == auth.org_id)
            ).all().__len__()
        }
        
    except Exception as e:
        logger.error(f"Failed to fetch search insights: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch search insights")


@router.get("/insights/stats")
def get_search_insights_stats(auth: AuthContext = Depends(get_current_user), session: Session = Depends(get_db)):
    """
    Get summary statistics on search insights.
    
    Returns:
        Counts by trends_momentum category
    """
    try:
        all_insights = session.exec(
            select(SearchInsight).where(SearchInsight.organization_id == auth.org_id)
        ).all()
        
        stats = {
            "total": len(all_insights),
            "rising": len([i for i in all_insights if i.trends_momentum == "rising"]),
            "falling": len([i for i in all_insights if i.trends_momentum == "falling"]),
            "steady": len([i for i in all_insights if i.trends_momentum == "steady"]),
            "no_data": len([i for i in all_insights if i.trends_momentum == "no_data"]),
        }
        
        return stats
        
    except Exception as e:
        logger.error(f"Failed to fetch search insights stats: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch search insights stats")
