from pathlib import Path

def extract_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("---", 3)
    if end == -1:
        return {}
    frontmatter = text[3:end].strip()
    data = {}
    for line in frontmatter.splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip()
    return data

def main() -> None:
    skill_files = sorted(Path("skills").rglob("SKILL.md"))
    lines = [
        "# Skills",
        "",
        "This file is generated by `scripts/generate_skill_index.py`.",
        "",
        "## Skill index",
        "",
        "| Skill | Path | Description |",
        "|---|---|---|",
    ]
    for path in skill_files:
        text = path.read_text(encoding="utf-8")
        fm = extract_frontmatter(text)
        name = fm.get("name", path.parent.name)
        description = fm.get("description", "")
        lines.append(f"| {name} | `{path}` | {description} |")
    Path("skills/README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote skills/README.md with {len(skill_files)} skills.")

if __name__ == "__main__":
    main()
